CREATE TABLE `lhc_instance_client` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `request` int(11) NOT NULL,
  `expires` int(11) NOT NULL,
  `suspended` int(11) NOT NULL,
  `terminate` int(11) NOT NULL,
  `address` varchar(30) NOT NULL,
  `email` varchar(250) NOT NULL,
  `status` int(11) NOT NULL,
  `time_zone` varchar(200) NOT NULL,
  `date_format` varchar(200) NOT NULL DEFAULT 'Y-m-d',
  `date_hour_format` varchar(200) NOT NULL DEFAULT 'H:i:s',
  `date_date_hour_format` varchar(200) NOT NULL DEFAULT 'Y-m-d H:i:s',
  `locale` varchar(10) NOT NULL,
  `siteaccess` varchar(3) NOT NULL,
  `is_reseller` tinyint(1) NOT NULL DEFAULT '0',
  `reseller_tite` varchar(50) NOT NULL,
  `reseller_max_instance_request` int(11) NOT NULL,
  `reseller_secret_hash` varchar(20) NOT NULL,
  `reseller_max_instances` int(11) NOT NULL,
  `reseller_id` int(11) NOT NULL,
  `reseller_request` int(11) NOT NULL,
  `reseller_suspended` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `address` (`address`),
  KEY `reseller_id` (`reseller_id`)
) ENGINE=InnoDB;